version: '2'

services:
  mysql:
    image: mysql:5
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mysql-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=secret
    depends_on:
      - mysql
  www:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html

volumes:
  mysql-data:
